spring.application.name=sharingfileweb

# Database config (MongoDB) sẽ được Load trực tiếp qua System.setProperty trong SharingfilewebApplication

# JWT Config
sharingfileweb.app.jwtSecret=${JWT_SECRET}
sharingfileweb.app.jwtExpirationMs=${JWT_EXPIRATION_MS}
sharingfileweb.app.jwtRefreshExpirationMs=${JWT_REFRESH_EXPIRATION_MS}

# File Upload Configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=1024MB

# Google OAuth2
sharingfileweb.app.googleClientId=${GOOGLE_CLIENT_ID}
sharingfileweb.app.googleClientSecret=${GOOGLE_CLIENT_SECRET}