spring.application.name=sharingfileweb

# Database config (MongoDB)
spring.data.mongodb.uri=mongodb://localhost:27017/sharingfileweb

# JWT Config
sharingfileweb.app.jwtSecret=======================SharingFileWebSecretKey===========================
sharingfileweb.app.jwtExpirationMs=86400000
sharingfileweb.app.jwtRefreshExpirationMs=604800000

# File Upload Configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=1024MB0
